language: python
sudo: false
python:
  - "3.5"
  - "3.6"
  
env:
  global:
    - GDALINST=$HOME/gdalinstall
    - GDALBUILD=$HOME/gdalbuild

# command to install dependencies
addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
    - gdal-bin
    - libproj-dev
    - libgdal-dev
    - proj-bin

before_install:
  - python -m pip install -U pip
  - python -m pip install wheel
  - export PATH=$GDALINST/gdal-$GDALVERSION/bin:$PATH
  - export LD_LIBRARY_PATH=$GDALINST/gdal-$GDALVERSION/lib:$LD_LIBRARY_PATH

install:
  - pip install -r requirements.txt
  - pip install .

# command to run tests
script:
  - pytest
