language: python
sudo: false
python:
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - python -m pip install -U pip
  - python -m pip install wheel
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update
  - sudo apt-get install python-gdal gdal-bin libproj-dev libgdal-dev

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .

# command to run tests
script:
  - pytest
