language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - sudo apt-get update
  - sudo apt-get install libgdal-dev
  - sudo apt-get install python3-gdal

addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .

# command to run tests
script:
  - pytest
