language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      sudo apt install python-gdal
    else
      sudo apt install python3-gdal
    fi

addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
    - libgdal-dev

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .

# command to run tests
script:
  - pytest
