language: python
sudo: false
python:
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - python -m pip install -U pip
  - python -m pip install wheel

addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
    - gdal-bin
    - libproj-dev
    - libgdal-dev
    - python-gdal

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .

# command to run tests
script:
  - pytest
