site_name: Pyspatialml
repo_url: https://github.com/stevenpawley/Pyspatialml

theme:
  name: "material"
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.integrate

plugins:
  - mkdocstrings
  - search

nav:
  - About: index.md
  - Usage overview: design.md
  - Quickstart: quickstart.md
  - Raster geoprocessing: geoprocessing.md
  - Plotting: plotting.md
  - Sampling: sampling.md
  - Spatial transformers: transformers.md
  - Example workflow: mlworkflow.md
  - API reference: api.md
